version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  flask:
    build: ./app
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
    depends_on:
      - db
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "8043:8043"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge
