name: octo

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build  # Строим все образы Docker

  deploy:
    runs-on: ubuntu-latest  
    needs: build  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1  

      - name: Deploy using Docker Compose
        run: docker-compose -f docker-compose.yml up -d 

      - name: Clean up
        run: docker-compose -f docker-compose.yml down
